name: coffee_cocoa
version: 1.0.0
config-version: 2
profile: coffee_cocoa
model-paths: [models]
target-path: target
clean-targets: [target]
models:
  coffee_cocoa:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
seeds:
  coffee_cocoa:
    trade_product_groups:
      +full_refresh: true
      +column_types:
        product_code: varchar
