minimum_pre_commit_version: "4.0.0"
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
      - id: conventional-commit
        name: Conventional commit message
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
